// Generated by CoffeeScript 1.12.6
(function() {
  var Auth, Dialog, E, React,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  React = require('react');

  E = require('react-script');

  Dialog = require('rc-dialog');

  Auth = (function(superClass) {
    extend(Auth, superClass);

    function Auth() {
      return Auth.__super__.constructor.apply(this, arguments);
    }

    Auth.prototype.render = function() {
      return E(Dialog, {}, E('iframe', {
        src: process.env.AUTHURL
      }));
    };

    return Auth;

  })(React.Component);

  module["export"] = App;

}).call(this);
